FROM golang:alpine

ARG GITHUB_BRANCH

RUN apk update && apk add git

RUN mkdir -p /go/src/github.com/byuoitav
ADD . /go/src/github.com/byuoitav/qsc-microservice

WORKDIR /go/src/github.com/byuoitav/qsc-microservice
RUN go get -d -v
RUN go install -v

CMD ["/go/bin/qsc-microservice"]

EXPOSE 8016
